Installation scripts for 0.12.0-beta.1 (remote shell, new CLI commands, new fluentd container, over commit memory configuration).

diff --git a/src/unms-cli b/src/unms-cli
--- a/src/unms-cli
+++ b/src/unms-cli
@@ -13,16 +13,18 @@ DATA_DIR=$( readlink -f ${APP_DIR}/../data )
 DOCKER_COMPOSE_FILENAME="docker-compose.yml"
 DOCKER_COMPOSE_FILE="${APP_DIR}/${DOCKER_COMPOSE_FILENAME}"
 
-if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
-  echo >&2 "Docker Compose file '${DOCKER_COMPOSE_FILE}' not found."
+# Log given message and exit.
+fail() {
+  echo >&2 "$1"
   exit 1
+}
+
+if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
+  fail "Docker Compose file '${DOCKER_COMPOSE_FILE}' not found."
 fi
 
 isRunning() {
-  status=$(docker-compose ps -q) || {
-    echo "Failed to determine UNMS status."
-    exit 1
-  }
+  status=$(docker-compose ps -q) || fail "Failed to determine UNMS status."
 
   if [ "${status}" = "" ]; then
     return 1
@@ -33,22 +35,43 @@ isRunning() {
 
 start() {
   echo "Starting UNMS..."
-  if ! docker-compose up -d; then
-    echo >&2 "Failed to start UNMS."
-    exit 1
-  fi
+  docker-compose up -d || fail "Failed to start UNMS."
   echo "UNMS started."
 }
 
 stop() {
   echo "Stopping UNMS..."
-  if ! docker-compose down; then
-    echo >&2 "Failed to stop UNMS."
-    exit 1
-  fi
+  docker-compose down || fail "Failed to stop UNMS."
   echo "UNMS stopped."
 }
 
+# Check redis append only file in ../data/redis/appendonly.aof and fix it if necessary.
+fix-redis-aof() {
+  docker-compose run --no-deps --rm --entrypoint /usr/local/bin/redis-check-aof redis --fix /data/db/appendonly.aof <<EOF
+Y
+EOF
+}
+
+# Shrink the redis append only file in ../data/redis/appendonly.aof.
+rewrite-redis-aof() {
+  docker-compose -p unms exec redis redis-cli bgrewriteaof || fail "Failed to rewrite redis appendonly file."
+}
+
+refresh-certificate() {
+  SSL_CERT=$(source unms.conf && echo "${SSL_CERT}")
+  if ! [ -e "../data/cert/domain" ]; then
+    fail "Domain file not found."
+  fi
+
+  DOMAIN=$(head -n 1 ../data/cert/domain)
+  if [ -n "${SSL_CERT}" ]; then
+    # Refresh custom certificate if it changed.
+    docker-compose -p unms exec nginx /cert.sh "${DOMAIN}"
+  else
+    # Refresh Let's Encrypt certificate.
+    docker-compose -p unms exec nginx /letsencrypt.sh "${DOMAIN}"
+  fi
+}
 
 (
   cd "${APP_DIR}"
@@ -81,6 +104,32 @@ stop() {
     exit 0
   fi
 
-  echo "Usage: unms-cli.sh [start|stop|restart]"
+  if [ "$*" = "fix-redis-aof" ]; then
+    if isRunning; then
+      fail "Please stop UNMS first with 'unms-cli stop'"
+    fi
+
+    fix-redis-aof
+    exit 0
+  fi
+
+  if [ "$*" = "rewrite-redis-aof" ]; then
+    if ! isRunning; then
+      fail "UNMS is not running"
+    fi
+
+    rewrite-redis-aof
+    exit 0
+  fi
+
+  if [ "$*" = "refresh-certificate" ]; then
+    if ! isRunning; then
+      echo "UNMS is not running"
+    fi
+    refresh-certificate
+    exit 0
+  fi
+
+  echo "Usage: unms-cli [start|stop|restart|fix-redis-aof|rewrite-redis-aof|refresh-certificate]"
   exit 0
 )
